const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),os=require('os'),path=require('path');const {Organizer,makePlan,key}=require('../src/organize');
const w=(app,title,index=0,extra={})=>({app,title,pid:100+index,index,minimized:false,rect:{x:30,y:40,w:800,h:600},...extra});const area={x:0,y:20,width:1440,height:850};
test('keeps current app and protects calls, terminals, unsaved and fullscreen windows',()=>{const items=[w('Editor','Work',0,{frontmost:true}),w('Viewer','Notes',1),w('Terminal','Build',2),w('Safari','Meeting',3),w('Writer','Draft',4,{edited:true}),w('Viewer','Full',5,{fullscreen:true})];const p=makePlan(items,[key(items[0])],area);assert.deepEqual(p.actions.filter(a=>a.kind==='minimize').map(a=>a.window.title),['Notes']);assert.equal(p.closable.length,0);});
test('tiles retained windows inside the available screen',()=>{const items=[w('Browser','Research',1),w('Editor','Report',2)];const p=makePlan(items,items.map(key),area);assert.equal(p.actions.length,2);assert.ok(p.actions.every(a=>a.rect.y>=area.y&&a.rect.x+a.rect.w<=area.width));});
function service(items,answer='no',dry=false){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'organize-test-'));const changes=[],questions=[];const o=new Organizer({file:path.join(dir,'layout.json'),inventory:async()=>items,change:async a=>{changes.push(a);return{}},choose:async()=>[key(items[0])],ask:async q=>{questions.push(q);return answer},area:()=>area,dry});return{o,changes,questions,dir};}
test('ordinary organisation never asks or closes, and undo restores the original geometry',async()=>{const x=service([w('Editor','Report',0,{frontmost:true}),w('Safari','News',1)]);await x.o.run('organise workspace');assert.equal(x.questions.length,0);assert.ok(x.changes.every(a=>a.kind!=='close'));await x.o.undo();const restores=x.changes.filter(a=>a.kind==='restore');assert.equal(restores.length,2);assert.deepEqual(restores[0].rect,{x:30,y:40,w:800,h:600});fs.rmSync(x.dir,{recursive:true});});
test('cleanup asks once, supports subset selection, and respects no',async()=>{for(const answer of ['no','2']){const x=service([w('Editor','Work',0,{frontmost:true}),w('Safari','News',1),w('Finder','Downloads',2)],answer);await x.o.run('clean workspace',{cleanup:true});assert.equal(x.questions.length,1);assert.deepEqual(x.changes.filter(a=>a.kind==='close').map(a=>a.window.title),answer==='2'?['Downloads']:[]);fs.rmSync(x.dir,{recursive:true});}});
test('a save dialog stops remaining closures without accepting or dismissing it',async()=>{const x=service([w('Editor','Work',0,{frontmost:true}),w('Safari','A',1),w('Safari','B',2)],'yes');x.o.change=async a=>{x.changes.push(a);return{dialog:a.kind==='close'}};await x.o.run('clean workspace',{cleanup:true});assert.equal(x.changes.filter(a=>a.kind==='close').length,1);fs.rmSync(x.dir,{recursive:true});});
test('unknown selection never causes the whole workspace to be minimised',async()=>{const x=service([w('Viewer','Page')]);x.o.choose=async()=>['invented'];await assert.rejects(x.o.run('organise workspace'),/which app/);assert.equal(x.changes.length,0);fs.rmSync(x.dir,{recursive:true});});
test('dry run preserves the previous undo snapshot',async()=>{const x=service([w('Editor','Work',0,{frontmost:true})],'no',true);fs.writeFileSync(x.o.file,'{"old":true}');await x.o.run('organise workspace');assert.deepEqual(x.o.read(),{old:true});fs.rmSync(x.dir,{recursive:true});});
