// Isolated capture of actual Stark renderers, TeachSession and Lesson/Tutor.
const {app,BrowserWindow,ipcMain,nativeTheme}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process');
const root=path.resolve(__dirname,'../..'),out=__dirname;
const cfg=require(path.join(root,'src/config')).loadConfig(path.join(os.homedir(),'Library/Application Support/Project Stark'));
const {TeachSession}=require(path.join(root,'src/teach'));
const {Apprentice}=require(path.join(root,'src/apprentice'));
const {Tutor,Lesson}=require(path.join(root,'src/tutor'));
const {avoid}=require(path.join(root,'src/avoid'));
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'stark-film-')));nativeTheme.themeSource='dark';
let win,box,target,avoidState={},teacher,lesson,frameStream,loop,frames=0;let activeTake;const evidence=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const js=code=>win.webContents.executeJavaScript(code);
const sandbox=code=>js(`(()=>{const document=globalThis.filmFrame.contentDocument,window=globalThis.filmFrame.contentWindow;${code}})()`);
function reposition(){if(!box)return;const r=avoid({island:box,screen:{x:0,y:0,w:1440,h:900},home:box.home,target,cursor:{x:0,y:0}},avoidState);avoidState=r.state;win.webContents.send('island-offset',{...r.offset,edge:r.edge});}
ipcMain.on('island-box',(_e,v)=>{box=v;reposition()});ipcMain.on('avoid-target',(_e,v)=>{if(v)target=v;reposition()});
ipcMain.handle('speak',()=>null);ipcMain.on('avoid-speech',()=>{});
async function scan(){return sandbox(`const es=[...document.querySelectorAll('button,a,input,textarea,select,h1,h2,td,th,.bill-meta span,.doc-total,.hint')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();const label=document.querySelector('label[for="'+e.id+'"]');return {role:e.tagName==='BUTTON'?'AXButton':e.tagName==='A'?'AXLink':['INPUT','TEXTAREA'].includes(e.tagName)?'AXTextField':e.tagName==='SELECT'?'AXPopUpButton':'AXStaticText',label:label?.textContent||e.getAttribute('aria-label')||e.innerText||e.id,value:['INPUT','TEXTAREA','SELECT'].includes(e.tagName)?e.value:undefined,x:r.x,y:r.y,w:r.width,h:r.height};});return {app:'Ledra',window:document.title,elements:es};`)}
async function move(selector){const r=await sandbox(`const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};`);await js(`document.getElementById('film-cursor').style.left='${r.x}px';document.getElementById('film-cursor').style.top='${r.y}px';`);await sleep(550);return r;}
async function click(selector){const r=await move(selector);if(teacher){await teacher.tick(await scan());teacher.onMouseDown(r.x,r.y)}if(lesson)lesson.onMouseDown(r.x,r.y);await sandbox(`document.querySelector(${JSON.stringify(selector)}).click();`);await sleep(400);}
async function input(selector,value){await move(selector);await sandbox(`const e=document.querySelector(${JSON.stringify(selector)});e.focus();e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));`);if(teacher){await teacher.tick(await scan());await sleep(1000);await teacher.tick(await scan())}if(lesson){lesson.replay.onScan(await scan());await sleep(1200);lesson.replay.onScan(await scan())}await sleep(450);}
async function waitAction(index){const end=Date.now()+30000;while(lesson.replay.index<index&&Date.now()<end)await sleep(200);if(lesson.replay.index<index)throw new Error('Lesson did not advance to action '+index);await sleep(500);}
async function record(name,fn){activeTake=name;frames=0;let stopped=false;frameStream=spawn('/opt/homebrew/bin/ffmpeg',['-y','-loglevel','error','-f','image2pipe','-vcodec','mjpeg','-r','15','-i','pipe:0','-an','-c:v','libx264','-preset','fast','-crf','17','-pix_fmt','yuv420p',path.join(out,'capture',name+'.mp4')]);let err='';frameStream.stderr.on('data',d=>err+=d);const done=new Promise((resolve,reject)=>frameStream.on('close',c=>c?reject(new Error(err)):resolve()));loop=(async()=>{while(!stopped){const t=Date.now();const image=await win.webContents.capturePage();if(!frameStream.stdin.write(image.toJPEG(94)))await new Promise(r=>frameStream.stdin.once('drain',r));frames++;await sleep(Math.max(0,67-(Date.now()-t)))}})();await fn();stopped=true;await loop;frameStream.stdin.end();await done;console.log('CAPTURED',name,frames/15);}
async function setup(set,bill){await sandbox(`window.localStorage.clear();window.localStorage.setItem('ledra.sandbox.set',JSON.stringify(${JSON.stringify(set)}));window.location.reload();`);await sleep(800);await sandbox(`window.location.hash='#/bills/${bill}';`);await sleep(600);}
function emit(step){evidence.push({...step,take:activeTake,at:frames/15});fs.writeFileSync(path.join(out,'capture','lesson-evidence.json'),JSON.stringify(evidence,null,2));win.webContents.send('guide-step',{...step,stepNo:step.stepNumber,rect:step.target?{x:step.target.x,y:step.target.y,w:step.target.w,h:step.target.h}:null,label:step.target?.label});console.log('LESSON',step.status,step.say||'(quiet)');}
app.whenReady().then(async()=>{
 win=new BrowserWindow({width:1440,height:900,useContentSize:true,show:false,webPreferences:{preload:path.join(root,'preload.js'),contextIsolation:true,nodeIntegration:false}});
 win.webContents.on('console-message',e=>{if(e.level==='error')console.error('RENDERER',e.message)});await win.loadFile(path.join(root,'renderer/index.html'));
 await js(`window.filmFrame=document.createElement('iframe');filmFrame.src=${JSON.stringify('file://'+path.join(root,'demo/app/index.html'))};filmFrame.style.cssText='position:absolute;inset:0;width:100%;height:100%;border:0;z-index:-1;background:#f5f6f8';document.body.prepend(filmFrame);const c=document.createElement('div');c.id='film-cursor';c.innerHTML='<svg width="26" height="32" viewBox="0 0 26 32"><path d="M3 2v24l6-6 5 10 5-3-5-9h9Z" fill="white" stroke="#15171a" stroke-width="2"/></svg>';c.style.cssText='position:absolute;left:1100px;top:730px;z-index:20000;pointer-events:none;transition:left .45s ease,top .45s ease';document.body.append(c);state.voice='off';state.micOff=true;state.resting=false;buddyEl.classList.add('awake');`);
 win.webContents.send('config',{voice:'off',canHear:false,wakeEnabled:false});win.webContents.send('layout',{mode:'island'});await sleep(1000);
 await setup('expert','BILL-2412');
 teacher=new TeachSession({title:'Review and code a machinery invoice',apprentice:new Apprentice(cfg.anthropicApiKey),scan,capture:async()=>null,askUser:async()=> 'Yes. New equipment costing more than €5,000 is capital expenditure. Use cost center 0400 and record an asset number before sending for approval.',status:t=>console.log('TEACH',t)});
 teacher.running=true;await teacher.tick(await scan());
 await record('teach',async()=>{win.webContents.send('teach-state',{recording:true,title:'Machinery invoice',startedAt:Date.now(),offRecord:false});await sleep(1800);teacher.onNarration('Review the line items first. This is new equipment costing over five thousand euros. Do not accept the OCR suggestion: code it to 0400, capital expenditure, and enter its asset number before approval. Repairs stay in 4711.');await input('#cost-center','0400');await input('#asset-no','AN-2026-184');await input('#note','New machinery · capital expenditure');await click('.actions .primary');await sleep(1600);win.webContents.send('teach-state',{recording:false});});
 const map=fs.existsSync(path.join(out,'capture','learned-skill.json'))?JSON.parse(fs.readFileSync(path.join(out,'capture','learned-skill.json'))).map:await teacher.finish();teacher.running=false;const skill={map,session:{title:teacher.title,events:teacher.events,qas:teacher.qas}};teacher=null;fs.writeFileSync(path.join(out,'capture','learned-skill.json'),JSON.stringify(skill,null,2));console.log('MAP',map.steps.map(s=>s.title));
 // Use a concise replay plan, derived from the real recorded actions. The actual learned map retains every rule.
 const ev=skill.session.events;const edits=ev.filter(e=>e.type==='edit');
 const eventStep=e=>Math.max(0,map.steps.findIndex(s=>s.event_ids.includes(e.id)))+1;
 const plan={actions:edits.filter(e=>['Cost center','Asset number'].includes(e.label)).map(e=>({event_id:e.id,step_number:eventStep(e),kind:'edit',say:e.label==='Cost center'?'This is new equipment. Use 0400 for capital expenditure.':'Now enter the asset number before approval.'}))};
 plan.actions.push({event_id:ev.find(e=>e.type==='click'&&e.label.includes('Send for approval'))?.id,step_number:map.steps.length,kind:'click',say:'Everything is checked. Send it for approval.'});
 for(const spot of [false,true]){
  await setup('trainee','BILL-2431');target=null;avoidState={};await js(`clearPointing();state.guiding=true;state.spotting=${spot};state.voice='off';document.getElementById('say').textContent='';document.getElementById('bubble').classList.add('hidden');document.getElementById('guide-bar').classList.remove('hidden');document.getElementById('guide-count').textContent=${JSON.stringify(spot?'Spotting':'Starting…')};`);
  lesson=new Lesson({skill,plan,scan,emit,tutor:new Tutor(cfg.anthropicApiKey,skill),snap:async()=>{const im=await win.webContents.capturePage();return {data:im.resize({width:1440}).toJPEG(85).toString('base64'),width:1440,height:900,display:{x:0,y:0,w:1440,h:900}}},spot,idleMs:90000});
  await record(spot?'spot':'learn',async()=>{await lesson.start();await sleep(spot?2200:3000);if(spot){await input('#cost-center','4711');let deadline=Date.now()+18000;while(!evidence.some(s=>s.take==='spot'&&s.flagged)&&Date.now()<deadline)await sleep(250);if(!evidence.some(s=>s.take==='spot'&&s.flagged))throw new Error('Spotting did not flag the wrong decision.');await sleep(6000)}await input('#cost-center','0400');await waitAction(1);await sleep(800);await input('#asset-no','AN-2026-219');await waitAction(2);await sleep(1000);await click('.actions .primary');await sleep(2200)});
  lesson.stop();lesson=null;await js(`state.guiding=false;clearPointing();`);
 }
 win.destroy();app.exit(0);
}).catch(e=>{console.error(e.message);fs.writeFileSync(path.join(out,'capture','capture-error.txt'),e.stack);app.exit(1)});
